/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Projeto.interfa;

import Projeto.ConectarBD;
import Projeto.DeletaBD;
import Projeto.EditaBD;
import Projeto.InsereBD;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Alves
 */
public class jifCadastroSalarios extends javax.swing.JInternalFrame {

    //instanciamento das classes necessárias
    InsereBD ins = new InsereBD();
    ConectarBD con = new ConectarBD();
    DeletaBD del = new DeletaBD();
    EditaBD edit = new EditaBD();
    Connection conexao = con.connectionMySql();
    String cod_sal = "";
    int acao;

    public jifCadastroSalarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jkkkk = new javax.swing.JLabel();
        jcod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        id_socio_sal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mes_ref_sal = new javax.swing.JTextField();
        novo_sal = new javax.swing.JButton();
        excluir_sal = new javax.swing.JButton();
        salvar_sal = new javax.swing.JButton();
        cancelar_sal = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        salvar_edit = new javax.swing.JButton();

        setBackground(new java.awt.Color(13, 39, 77));
        setClosable(true);
        setTitle("Cadastro Salarios");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jkkkk.setForeground(new java.awt.Color(255, 0, 0));
        jkkkk.setText("Cod");

        jcod.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(13, 36, 125));
        jLabel1.setText("Id Socio");

        id_socio_sal.setEnabled(false);
        id_socio_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_socio_salActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(13, 36, 125));
        jLabel2.setText("Mes de Referência");

        mes_ref_sal.setEnabled(false);

        novo_sal.setBackground(new java.awt.Color(13, 36, 125));
        novo_sal.setForeground(new java.awt.Color(255, 255, 255));
        novo_sal.setText("Novo");
        novo_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novo_salActionPerformed(evt);
            }
        });

        excluir_sal.setBackground(new java.awt.Color(13, 36, 125));
        excluir_sal.setForeground(new java.awt.Color(255, 255, 255));
        excluir_sal.setText("Excluir");
        excluir_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_salActionPerformed(evt);
            }
        });

        salvar_sal.setBackground(new java.awt.Color(13, 36, 125));
        salvar_sal.setForeground(new java.awt.Color(255, 255, 255));
        salvar_sal.setText("Salvar");
        salvar_sal.setEnabled(false);
        salvar_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_salActionPerformed(evt);
            }
        });

        cancelar_sal.setBackground(new java.awt.Color(13, 36, 125));
        cancelar_sal.setForeground(new java.awt.Color(255, 255, 255));
        cancelar_sal.setText("Cancelar");
        cancelar_sal.setEnabled(false);
        cancelar_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_salActionPerformed(evt);
            }
        });

        editar.setBackground(new java.awt.Color(13, 36, 125));
        editar.setForeground(new java.awt.Color(255, 255, 255));
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        salvar_edit.setBackground(new java.awt.Color(13, 36, 125));
        salvar_edit.setForeground(new java.awt.Color(255, 255, 255));
        salvar_edit.setText("Salvar Edit");
        salvar_edit.setEnabled(false);
        salvar_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jkkkk)
                    .addComponent(id_socio_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(mes_ref_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cancelar_sal)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(novo_sal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(excluir_sal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salvar_edit))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcod, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(287, 287, 287)
                                .addComponent(salvar_sal)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jkkkk)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(salvar_sal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_socio_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar_sal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mes_ref_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novo_sal)
                    .addComponent(editar)
                    .addComponent(excluir_sal)
                    .addComponent(salvar_edit))
                .addGap(0, 278, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(600, 20, 462, 255);
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_editActionPerformed
        //configuralçao da segunda tela do editar que realiza a edição no BD
        cod_sal = jcod.getText().trim();
        JOptionPane.showMessageDialog(null, "Favor Inserir dados do Socio!");
        editarSegundaTela();
    }//GEN-LAST:event_salvar_editActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        editar();
        acao = 2;
    }//GEN-LAST:event_editarActionPerformed

    private void cancelar_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_salActionPerformed
        // TODO add your handling code here:
        cancelar();
    }//GEN-LAST:event_cancelar_salActionPerformed

    private void salvar_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_salActionPerformed
        int cod;

        if (acao == 1) {

            try {

                String id_socio = id_socio_sal.getText().trim();
                String mes_ref = mes_ref_sal.getText().trim();
                if (id_socio != null && !id_socio.isEmpty() && mes_ref != null && !mes_ref.isEmpty()) {

                    int id_socio_sal = Integer.parseInt(id_socio);

                    ins.insereSalario(conexao, id_socio_sal, mes_ref);
                    //variável que recebe a primary key do CLiente
                    cod = ins.retornaPrimaryKey(conexao);
                    //Insere na interface gráfica o valor da primary key
                    jcod.setText(String.valueOf(cod));
                    salvar();
                    JOptionPane.showMessageDialog(null, "Inserido com sucesso");
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher todos os Campos");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao inserir!" + e);
            }
        } else if (acao == 2) {

            try {

                if (cod_sal != null && !cod_sal.isEmpty()) {

                    int cod1 = Integer.parseInt(cod_sal);
                    String id_socio = id_socio_sal.getText().trim();
                    String mes_ref = mes_ref_sal.getText().trim();
                    int id_socio_sal = Integer.parseInt(id_socio);

                    edit.editaSalario(conexao, id_socio_sal, mes_ref, cod1);

                    JOptionPane.showMessageDialog(null, "Editado com sucesso");
                    salvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher o campo Cod! ");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Editar!" + e);
            }
            // segue o padrão anterior  (verificação do botão Excluir)

        } else if (acao == 3) {

            try {

                cod_sal = jcod.getText().trim();

                if (cod_sal != null && !cod_sal.isEmpty()) {

                    int codNf = Integer.parseInt(cod_sal);
                    del.deletaNf(conexao, codNf);

                    JOptionPane.showMessageDialog(null, "Deletado com sucesso");
                    salvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher o campo Cod! ");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Deletar!" + e);
            }

        }
    }//GEN-LAST:event_salvar_salActionPerformed

    private void excluir_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_salActionPerformed
        // TODO add your handling code here:
        excluir();
        acao = 2;
    }//GEN-LAST:event_excluir_salActionPerformed

    private void novo_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novo_salActionPerformed

        novo();
        acao = 1;
    }//GEN-LAST:event_novo_salActionPerformed

    private void id_socio_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_socio_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_socio_salActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar_sal;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir_sal;
    private javax.swing.JTextField id_socio_sal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jcod;
    private javax.swing.JLabel jkkkk;
    private javax.swing.JTextField mes_ref_sal;
    private javax.swing.JButton novo_sal;
    private javax.swing.JButton salvar_edit;
    private javax.swing.JButton salvar_sal;
    // End of variables declaration//GEN-END:variables

    public void novo() {
        id_socio_sal.setEnabled(true);
        mes_ref_sal.setEnabled(true);
        cancelar_sal.setEnabled(true);
        salvar_sal.setEnabled(true);
        id_socio_sal.setText("");
        mes_ref_sal.setText("");

    }

    public void excluir() {
        id_socio_sal.setEnabled(true);
        mes_ref_sal.setEnabled(true);
        cancelar_sal.setEnabled(true);
        salvar_sal.setEnabled(true);
        id_socio_sal.setText("");
        mes_ref_sal.setText("");

    }

    public void editar() {
        id_socio_sal.setEnabled(false);
        jcod.setEnabled(true);
        mes_ref_sal.setEnabled(false);
        salvar_sal.setEnabled(false);
        excluir_sal.setEnabled(true);
        cancelar_sal.setEnabled(true);
        salvar_edit.setEnabled(true);

    }

    public void editarSegundaTela() {

        jcod.setEnabled(false);
        id_socio_sal.setEnabled(true);
        mes_ref_sal.setEnabled(true);
        salvar_sal.setEnabled(true);
        excluir_sal.setEnabled(true);
        cancelar_sal.setEnabled(true);
        salvar_edit.setEnabled(false);

    }

    public void cancelar() {
        id_socio_sal.setEnabled(false);
        mes_ref_sal.setEnabled(false);
        cancelar_sal.setEnabled(false);
        salvar_sal.setEnabled(false);
        id_socio_sal.setText("");
        mes_ref_sal.setText("");

    }

    public void salvar() {
        id_socio_sal.setEnabled(false);
        mes_ref_sal.setEnabled(false);
        cancelar_sal.setEnabled(false);
        salvar_sal.setEnabled(false);

    }

} // fim da classe principal

