package Projeto.interfa;

import Projeto.ConectarBD;
import Projeto.DeletaBD;
import Projeto.EditaBD;
import Projeto.InsereBD;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus Alves
 */
public class jifCadastroNf extends javax.swing.JInternalFrame {

    //instanciamento das classes necessárias
    InsereBD ins = new InsereBD();
    ConectarBD con = new ConectarBD();
    DeletaBD del = new DeletaBD();
    EditaBD edit = new EditaBD();
    Connection conexao = con.connectionMySql();
    //variável auxiliar para definir o tipo do botão (novo, editar, excluir)
    int acao;
    //variável auxiliar para o botão editar
    String cod_nf = "";

    public jifCadastroNf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numero_nf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id_pedido_nf = new javax.swing.JTextField();
        novo = new javax.swing.JButton();
        editar_nf = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        salvar_edit = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Nota Fiscal");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Cod");

        jcod.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(13, 36, 125));
        jLabel1.setText("Numero da Nota Fiscal");

        numero_nf.setEnabled(false);

        jLabel2.setForeground(new java.awt.Color(13, 36, 125));
        jLabel2.setText("Id do Pedido");

        id_pedido_nf.setEnabled(false);

        novo.setBackground(new java.awt.Color(13, 36, 125));
        novo.setForeground(new java.awt.Color(255, 255, 255));
        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });

        editar_nf.setBackground(new java.awt.Color(13, 36, 125));
        editar_nf.setForeground(new java.awt.Color(255, 255, 255));
        editar_nf.setText("Editar");
        editar_nf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_nfActionPerformed(evt);
            }
        });

        excluir.setBackground(new java.awt.Color(13, 36, 125));
        excluir.setForeground(new java.awt.Color(255, 255, 255));
        excluir.setText("Excluir");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        salvar.setBackground(new java.awt.Color(13, 36, 125));
        salvar.setForeground(new java.awt.Color(255, 255, 255));
        salvar.setText("Salvar");
        salvar.setEnabled(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(13, 36, 125));
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        salvar_edit.setBackground(new java.awt.Color(13, 36, 125));
        salvar_edit.setForeground(new java.awt.Color(255, 255, 255));
        salvar_edit.setText("Salvar Edit");
        salvar_edit.setEnabled(false);
        salvar_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcod, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(id_pedido_nf, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(numero_nf, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(cancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editar_nf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvar_edit)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero_nf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_pedido_nf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novo)
                    .addComponent(editar_nf)
                    .addComponent(excluir)
                    .addComponent(salvar_edit))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(600, 20, 457, 290);
    }// </editor-fold>//GEN-END:initComponents

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        excluir();
        acao = 3;
    }//GEN-LAST:event_excluirActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        acao = 1;
        novo();
    }//GEN-LAST:event_novoActionPerformed

    private void editar_nfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_nfActionPerformed
        editar();
        acao = 2;
    }//GEN-LAST:event_editar_nfActionPerformed

    private void salvar_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_editActionPerformed
        //configuralçao da segunda tela do editar que realiza a edição no BD
        cod_nf = jcod.getText().trim();
        JOptionPane.showMessageDialog(null, "Favor Inserir dados do Socio!");
        editarSegundaTela();
    }//GEN-LAST:event_salvar_editActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        //variável que recebe a primary key do BD
        int cod;
        //condição que verifica o tipo do botão (nesse caso, botão novo)
        if (acao == 1) {

            try {
                //armazenamento do que foi digitado nos campos em váriáveis
                String numeroNf = numero_nf.getText().trim();
                String idPed = id_pedido_nf.getText().trim();

                // verifica se os campos estão nulos
                if (numeroNf != null && !numeroNf.isEmpty() && idPed != null && !idPed.isEmpty()) {
                    //passando por parametros para a função que insere os clientes no BD
                    int idPedido = Integer.parseInt(idPed);
                    ins.insereNf(conexao, numeroNf, idPedido);
                    //variável que recebe a primary key do CLiente
                    cod = ins.retornaPrimaryKey(conexao);
                    //Insere na interface gráfica o valor da primary key
                    jcod.setText(String.valueOf(cod));

                    JOptionPane.showMessageDialog(null, "Inserido com sucesso");
                    salvar();

                    //caso tenha algum campo vazio apresenta uma mensagem informando para inserir todos os campos e o BD não é preenchido    
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher todos os Campos");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao inserir!" + e);
            }

            // segue o padrão anterior  (verificação do botão Editar)
        } else if (acao == 2) {

            try {

                if (cod_nf != null && !cod_nf.isEmpty()) {

                    int cod1 = Integer.parseInt(cod_nf);
                    String numeroNf = numero_nf.getText().trim();
                    String idPed = id_pedido_nf.getText().trim();
                    int idPedido = Integer.parseInt(idPed);

                    edit.editaNf(conexao, numeroNf, idPedido, cod1);

                    JOptionPane.showMessageDialog(null, "Socio Editado com sucesso");
                    salvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher o campo CNPJ! ");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Editar!" + e);
            }
            // segue o padrão anterior  (verificação do botão Excluir)            

        } else if (acao == 3) {

            try {

                cod_nf = jcod.getText().trim();

                if (cod_nf != null && !cod_nf.isEmpty()) {
                    
                    int codNf = Integer.parseInt(cod_nf);
                    del.deletaNf(conexao, codNf);

                    JOptionPane.showMessageDialog(null, "Socio deletado com sucesso");
                    salvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher o campo CNPJ! ");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Deletar!" + e);
            }

        }
    }//GEN-LAST:event_salvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton editar_nf;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField id_pedido_nf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jcod;
    private javax.swing.JButton novo;
    private javax.swing.JTextField numero_nf;
    private javax.swing.JButton salvar;
    private javax.swing.JButton salvar_edit;
    // End of variables declaration//GEN-END:variables

    public void novo() {
        jcod.setEnabled(false);
        numero_nf.setEnabled(true);
        id_pedido_nf.setEnabled(true);
        salvar.setEnabled(true);
        excluir.setEnabled(true);
        cancelar.setEnabled(true);
        salvar_edit.setEnabled(false);
        numero_nf.setText("");
        id_pedido_nf.setText("");
    }

    public void editar() {
        numero_nf.setEnabled(false);
        jcod.setEnabled(true);
        id_pedido_nf.setEnabled(false);
        salvar.setEnabled(false);
        excluir.setEnabled(true);
        cancelar.setEnabled(true);
        salvar_edit.setEnabled(true);
        numero_nf.setText("");
        id_pedido_nf.setText("");
    }

    public void editarSegundaTela() {

        jcod.setEnabled(false);
        numero_nf.setEnabled(true);
        id_pedido_nf.setEnabled(true);
        salvar.setEnabled(true);
        excluir.setEnabled(true);
        cancelar.setEnabled(true);
        salvar_edit.setEnabled(false);

    }

    public void excluir() {
        jcod.setEnabled(true);
        numero_nf.setEnabled(false);
        id_pedido_nf.setEnabled(false);
        salvar.setEnabled(true);
        excluir.setEnabled(true);
        cancelar.setEnabled(true);
        salvar_edit.setEnabled(false);
    }

    public void cancelar() {
        numero_nf.setEnabled(false);
        id_pedido_nf.setEnabled(false);
        salvar.setEnabled(false);
        cancelar.setEnabled(false);
        salvar_edit.setEnabled(false);
        numero_nf.setText("");
        id_pedido_nf.setText("");

    }

    public void salvar() {
        numero_nf.setEnabled(false);
        id_pedido_nf.setEnabled(false);
        salvar.setEnabled(false);
        cancelar.setEnabled(false);
        salvar_edit.setEnabled(false);

    }

}



