package Projeto.interfa;

import Projeto.ConectarBD;
import Projeto.DeletaBD;
import Projeto.EditaBD;
import Projeto.InsereBD;
import java.sql.Connection;
import javax.swing.JOptionPane;

public class jifCadastroProdutos extends javax.swing.JInternalFrame {

    InsereBD ins = new InsereBD();
    ConectarBD con = new ConectarBD();
    DeletaBD del = new DeletaBD();
    EditaBD edit = new EditaBD();
    Connection conexao = con.connectionMySql();

    int acao;
    String cod_prod = "";

    public jifCadastroProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        valor_produto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        desc_produto = new javax.swing.JTextField();
        salvar_produto = new javax.swing.JButton();
        cancelar_produto = new javax.swing.JButton();
        novo_produto = new javax.swing.JButton();
        excluir_produto = new javax.swing.JButton();
        editar_produto = new javax.swing.JButton();
        salvar_edit = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Cadastro de Produtos");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Cod");

        jcod.setEnabled(false);

        jLabel1.setForeground(new java.awt.Color(13, 39, 77));
        jLabel1.setText("Valor do Produto");

        valor_produto.setEnabled(false);
        valor_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor_produtoActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(13, 39, 77));
        jLabel2.setText("Descrição do Produto");

        desc_produto.setEnabled(false);
        desc_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desc_produtoActionPerformed(evt);
            }
        });

        salvar_produto.setBackground(new java.awt.Color(13, 39, 77));
        salvar_produto.setForeground(new java.awt.Color(255, 255, 255));
        salvar_produto.setText("Salvar");
        salvar_produto.setEnabled(false);
        salvar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_produtoActionPerformed(evt);
            }
        });

        cancelar_produto.setBackground(new java.awt.Color(13, 39, 77));
        cancelar_produto.setForeground(new java.awt.Color(255, 255, 255));
        cancelar_produto.setText("Cancelar");
        cancelar_produto.setEnabled(false);
        cancelar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_produtoActionPerformed(evt);
            }
        });

        novo_produto.setBackground(new java.awt.Color(13, 39, 77));
        novo_produto.setForeground(new java.awt.Color(255, 255, 255));
        novo_produto.setText("Novo");
        novo_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novo_produtoActionPerformed(evt);
            }
        });

        excluir_produto.setBackground(new java.awt.Color(13, 39, 77));
        excluir_produto.setForeground(new java.awt.Color(255, 255, 255));
        excluir_produto.setText("Excluir");
        excluir_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_produtoActionPerformed(evt);
            }
        });

        editar_produto.setBackground(new java.awt.Color(13, 39, 77));
        editar_produto.setForeground(new java.awt.Color(255, 255, 255));
        editar_produto.setText("Editar");
        editar_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_produtoActionPerformed(evt);
            }
        });

        salvar_edit.setBackground(new java.awt.Color(13, 39, 77));
        salvar_edit.setText("Salvar Edit");
        salvar_edit.setEnabled(false);
        salvar_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcod, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar_produto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(valor_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(desc_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvar_produto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(novo_produto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar_produto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluir_produto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvar_edit)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(salvar_produto))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar_produto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valor_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desc_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novo_produto)
                    .addComponent(excluir_produto)
                    .addComponent(editar_produto)
                    .addComponent(salvar_edit))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(600, 30, 420, 297);
    }// </editor-fold>//GEN-END:initComponents

    private void valor_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor_produtoActionPerformed

    private void novo_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novo_produtoActionPerformed
        novo();
        acao = 1;
    }//GEN-LAST:event_novo_produtoActionPerformed

    private void desc_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desc_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desc_produtoActionPerformed

    private void editar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_produtoActionPerformed
        editar();
        acao = 2;
    }//GEN-LAST:event_editar_produtoActionPerformed

    private void excluir_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_produtoActionPerformed
        excluir();
        acao = 3;
    }//GEN-LAST:event_excluir_produtoActionPerformed

    private void salvar_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_editActionPerformed
        cod_prod = jcod.getText().trim();
        JOptionPane.showMessageDialog(null, "Favor Inserir dados do Cliente!");
        editarSegundaTela();
    }//GEN-LAST:event_salvar_editActionPerformed

    private void cancelar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_produtoActionPerformed
        cancelar();
    }//GEN-LAST:event_cancelar_produtoActionPerformed

    private void salvar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_produtoActionPerformed
        int cod;
        if (acao == 1) {

            try {
                //armazenamento do que foi digitado nos campos em váriáveis
                String vp = valor_produto.getText().trim();
                String desc = desc_produto.getText().trim();

                // verifica se os campos estão nulos
                if (vp != null && !vp.isEmpty() && desc != null && !desc.isEmpty()) {
                    //passando por parametros para a função que insere os clientes no BD
                    double vp1 = Double.parseDouble(vp);
                    ins.insereProd(conexao, vp1, desc);
                    //variável que recebe a primary key do CLiente
                    cod = ins.retornaPrimaryKey(conexao);
                    //Insere na interface gráfica o valor da primary key
                    jcod.setText(String.valueOf(cod));

                    JOptionPane.showMessageDialog(null, "Inserido com sucesso");
                    
                    salvar();

                    //caso tenha algum campo vazio apresenta uma mensagem informando para inserir todos os campos e o BD não é preenchido    
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher todos os Campos");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao inserir!" + e);
            }

            // segue o padrão anterior  (verificação do botão Editar)
        } else if (acao == 2) {

            try {

                if (cod_prod != null && !cod_prod.isEmpty()) {

                    int cod1 = Integer.parseInt(cod_prod);
                    String vp = valor_produto.getText().trim();
                    String desc = desc_produto.getText().trim();

                    double vp1 = Double.parseDouble(vp);

                    edit.editaProd(conexao, vp1, desc, cod1);

                    JOptionPane.showMessageDialog(null, "Produto Editado com sucesso");
                    salvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher o campo CNPJ! ");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Editar!" + e);
            }
            // segue o padrão anterior  (verificação do botão Excluir)            

        } else if (acao == 3) {

            try {

                if (cod_prod != null && !cod_prod.isEmpty()) {
                    int cod1 = Integer.parseInt(cod_prod);

                    del.deletaProd(conexao, cod1);

                    JOptionPane.showMessageDialog(null, "Produto deletado com sucesso");
                    salvar();
                } else {
                    JOptionPane.showMessageDialog(null, "Favor Prencher o campo CNPJ! ");

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao Deletar!" + e);
            }

        }

    }//GEN-LAST:event_salvar_produtoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar_produto;
    private javax.swing.JTextField desc_produto;
    private javax.swing.JButton editar_produto;
    private javax.swing.JButton excluir_produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jcod;
    private javax.swing.JButton novo_produto;
    private javax.swing.JButton salvar_edit;
    private javax.swing.JButton salvar_produto;
    private javax.swing.JTextField valor_produto;
    // End of variables declaration//GEN-END:variables

    public void novo() {
        cancelar_produto.setEnabled(true);
        salvar_produto.setEnabled(true);
        jcod.setEnabled(false);
        desc_produto.setEnabled(true);
        valor_produto.setEnabled(true);
        salvar_edit.setEnabled(false);
        jcod.setText("");
        desc_produto.setText("");
        valor_produto.setText("");

    }

    public void editar() {
        cancelar_produto.setEnabled(true);
        salvar_produto.setEnabled(false);
        jcod.setEnabled(true);
        desc_produto.setEnabled(false);
        valor_produto.setEnabled(false);
        salvar_edit.setEnabled(true);
        jcod.setText("");
        desc_produto.setText("");
        valor_produto.setText("");

    }

    public void editarSegundaTela() {
        cancelar_produto.setEnabled(true);
        salvar_produto.setEnabled(true);
        jcod.setEnabled(false);
        desc_produto.setEnabled(true);
        valor_produto.setEnabled(true);
        salvar_edit.setEnabled(false);

    }

    public void excluir() {
        cancelar_produto.setEnabled(true);
        salvar_produto.setEnabled(true);
        jcod.setEnabled(true);
        desc_produto.setEnabled(true);
        valor_produto.setEnabled(true);
        salvar_edit.setEnabled(false);
        jcod.setText("");
        desc_produto.setText("");
        valor_produto.setText("");

    }

    public void cancelar() {
        cancelar_produto.setEnabled(false);
        salvar_produto.setEnabled(false);
        jcod.setEnabled(false);
        desc_produto.setEnabled(false);
        valor_produto.setEnabled(false);
        salvar_edit.setEnabled(false);
        jcod.setText("");
        desc_produto.setText("");
        valor_produto.setText("");

    }

    public void salvar() {
        cancelar_produto.setEnabled(false);
        salvar_produto.setEnabled(false);
        jcod.setEnabled(false);
        desc_produto.setEnabled(false);
        valor_produto.setEnabled(false);
        salvar_edit.setEnabled(false);

    }

}
